baseURL = 'https://example.org/'
languageCode = 'ja'
title = 'Hello KEN010'
theme = 'ananke'

[[menu.main]]
  identifier = "home"
  name = "ホーム"
  url = "/"
  weight = 10
[[menu.main]]
  identifier = "about"
  name = "会社概要"
  url = "/about"
  weight = 20
[[menu.main]]
  identifier = "post"
  name = "日記"
  url = "/post"
  weight = 30
[[menu.main]]
  identifier = "contact"
  name = "お問い合わせ"
  url = "/contact"
  weight = 40

[params]
  customCSS = ["css/custom.css"]